/*
 * LEDMXD_Config.h
 *
 *  Created on: May 17, 2023
 *      Author: Abdulrahman
 */

#ifndef LEDMXD_CONFIG_H_
#define LEDMXD_CONFIG_H_

/*Options =  GPIOA,PIN0:PIN15
 *           GPIOB
 *           GPIOC
 *           */

#define LEDMXD_ROW0_PIN    LEDMXD_ROW0,OUTPUT
#define LEDMXD_ROW1_PIN    LEDMXD_ROW1,OUTPUT
#define LEDMXD_ROW2_PIN    LEDMXD_ROW2,OUTPUT
#define LEDMXD_ROW3_PIN    LEDMXD_ROW3,OUTPUT
#define LEDMXD_ROW4_PIN    LEDMXD_ROW4,OUTPUT
#define LEDMXD_ROW5_PIN    LEDMXD_ROW5,OUTPUT
#define LEDMXD_ROW6_PIN    LEDMXD_ROW6,OUTPUT
#define LEDMXD_ROW7_PIN    LEDMXD_ROW7,OUTPUT


#define LEDMXD_COL0_PIN    LEDMXD_COL0,OUTPUT
#define LEDMXD_COL1_PIN    LEDMXD_COL1,OUTPUT
#define LEDMXD_COL2_PIN    LEDMXD_COL2,OUTPUT
#define LEDMXD_COL3_PIN    LEDMXD_COL3,OUTPUT
#define LEDMXD_COL4_PIN    LEDMXD_COL4,OUTPUT
#define LEDMXD_COL5_PIN    LEDMXD_COL5,OUTPUT
#define LEDMXD_COL6_PIN    LEDMXD_COL6,OUTPUT
#define LEDMXD_COL7_PIN    LEDMXD_COL7,OUTPUT


#define LEDMXD_COL0    GPIOB_,PIN0
#define LEDMXD_COL1    GPIOB_,PIN1
#define LEDMXD_COL2    GPIOB_,PIN2
#define LEDMXD_COL3    GPIOB_,PIN3
#define LEDMXD_COL4    GPIOB_,PIN4
#define LEDMXD_COL5    GPIOB_,PIN5
#define LEDMXD_COL6    GPIOB_,PIN6
#define LEDMXD_COL7    GPIOB_,PIN7


#define LEDMXD_ROW0    GPIOA_,PIN0
#define LEDMXD_ROW1    GPIOA_,PIN1
#define LEDMXD_ROW2    GPIOA_,PIN2
#define LEDMXD_ROW3    GPIOA_,PIN3
#define LEDMXD_ROW4    GPIOA_,PIN4
#define LEDMXD_ROW5    GPIOA_,PIN5
#define LEDMXD_ROW6    GPIOA_,PIN6
#define LEDMXD_ROW7    GPIOA_,PIN7



#endif /* LEDMXD_CONFIG_H_ */
